name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  version-control-and-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  compile:
    needs: version-control-and-ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile code
        run: |
          echo "Compilação não é necessária ou não configurada."

  tests:
    needs: version-control-and-ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          PASSWORD: ${{ secrets.PASSWORD }}
          NEW_PASSWORD: ${{ secrets.NEW_PASSWORD }}
        run: |
          python -m unittest discover -s test -p '*_test.py'

  bandit:
    needs: version-control-and-ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -o bandit-report.html || true

      - name: List files
        run: |
          ls -l

      - name: Upload Bandit report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.html

  dependency-check:
    needs: version-control-and-ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
          unzip dependency-check-10.0.4-release.zip
          sudo mv dependency-check/bin/dependency-check.sh /usr/local/bin/dependency-check

      - name: Run OWASP Dependency Check
        run: |
          dependency-check --project "Task-Manager-using-Flask" --scan . --out dependency-check-report.html || true

      - name: List files
        run: |
          ls -l

      - name: Upload OWASP Dependency Check report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report.html

  start_app:
    needs: version-control-and-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start application
        run: |
          nohup python run.py &

          zap_scan:
            needs: [version-control-and-ci, start_app]
            runs-on: ubuntu-latest
            env:
              SECRET_KEY: ${{ secrets.SECRET_KEY }}
              PASSWORD: ${{ secrets.PASSWORD }}
              NEW_PASSWORD: ${{ secrets.NEW_PASSWORD }}
            steps:
              - name: Checkout code
                uses: actions/checkout@v2
                
              - name: Wait for application to be ready
                run: |
                  for i in {1..10}; do
                    curl -s http://127.0.0.1:5000 && break || sleep 5;
                  done
        
              - name: Run ZAP Baseline Scan
                uses: zaproxy/action-baseline@v0.12.0
                with:
                  target: 'http://127.0.0.1:5000'  # Mantenha como 127.0.0.1
                  fail_action: true
        